// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus.Gateway.Data;

#nullable disable

namespace Nexus.Gateway.Migrations
{
    [DbContext(typeof(NexusContext))]
    [Migration("20260616202713_AddPluginSourceType")]
    partial class AddPluginSourceType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Nexus.Gateway.Models.AppSetting", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AdSyncInterval")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AnimationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoRefreshInterval")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CpuAlertThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultLandingPage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("MfaRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotificationEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RamAlertThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionTimeout")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TelemetryRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UiDensity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = "global",
                            AdSyncInterval = 60,
                            AnimationsEnabled = true,
                            AutoRefreshInterval = 30,
                            CpuAlertThreshold = 90,
                            DefaultLandingPage = "dashboard",
                            Language = "en-US",
                            LogLevel = "info",
                            MfaRequired = false,
                            NotificationEmail = "",
                            RamAlertThreshold = 90,
                            SessionTimeout = 30,
                            TelemetryRetentionDays = 30,
                            Theme = "dark",
                            UiDensity = "comfortable",
                            WebhookUrl = ""
                        });
                });

            modelBuilder.Entity("Nexus.Gateway.Models.DiskModel", b =>
                {
                    b.Property<int>("DbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartitionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SizeGB")
                        .HasColumnType("REAL");

                    b.HasKey("DbId");

                    b.HasIndex("ServerIp");

                    b.ToTable("Disks");
                });

            modelBuilder.Entity("Nexus.Gateway.Models.InstalledAppEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstallDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeMB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UninstallString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerIp");

                    b.ToTable("InstalledApps");
                });

            modelBuilder.Entity("Nexus.Gateway.Models.NotificationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Nexus.Gateway.Models.PerfSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cpu")
                        .HasColumnType("REAL");

                    b.Property<double>("DiskR")
                        .HasColumnType("REAL");

                    b.Property<double>("DiskW")
                        .HasColumnType("REAL");

                    b.Property<double>("Mem")
                        .HasColumnType("REAL");

                    b.Property<double>("NetIn")
                        .HasColumnType("REAL");

                    b.Property<double>("NetOut")
                        .HasColumnType("REAL");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("T")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServerIp", "T");

                    b.ToTable("PerfSamples");
                });

            modelBuilder.Entity("Nexus.Gateway.Models.PluginEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScriptContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScriptType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Plugins");
                });

            modelBuilder.Entity("Nexus.Gateway.Models.ProcessModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cpu")
                        .HasColumnType("REAL");

                    b.Property<int>("Handles")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MemMB")
                        .HasColumnType("REAL");

                    b.Property<double>("MemPct")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Pid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Threads")
                        .HasColumnType("INTEGER");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerIp");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("Nexus.Gateway.Models.SecurityEventLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerIp");

                    b.HasIndex("ServerIp", "TimeCreated");

                    b.ToTable("SecurityEventLogs");
                });

            modelBuilder.Entity("Nexus.Gateway.Models.SecuritySnapshot", b =>
                {
                    b.Property<string>("ServerIp")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLogins24h")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalAdminsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenPortsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ServerIp");

                    b.ToTable("SecuritySnapshots");
                });

            modelBuilder.Entity("Nexus.Gateway.Models.Server", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("Cpu")
                        .HasColumnType("REAL");

                    b.Property<double>("Disk")
                        .HasColumnType("REAL");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdFetched")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Mem")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Uptime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("Nexus.Gateway.Models.VolumeModel", b =>
                {
                    b.Property<int>("DbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiskId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Letter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SizeGB")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("UsedGB")
                        .HasColumnType("REAL");

                    b.HasKey("DbId");

                    b.HasIndex("ServerIp");

                    b.ToTable("Volumes");
                });

            modelBuilder.Entity("Nexus.Gateway.Models.WindowsRoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServerRoles");
                });

            modelBuilder.Entity("Nexus.Gateway.Models.WindowsUpdateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("MaxDownloadSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServerUpdates");
                });
#pragma warning restore 612, 618
        }
    }
}
