// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus.Gateway.Data;

#nullable disable

namespace Nexus.Gateway.Migrations
{
    [DbContext(typeof(NexusContext))]
    [Migration("20260712123629_AddProcessTelemetry")]
    partial class AddProcessTelemetry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Nexus.Gateway.Models.AppSetting", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AdSyncInterval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlertQuietHours")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AnimationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppLoginMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppSubtitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AuditLoggingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoRefreshInterval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyLogoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CpuAlertThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DashboardLayout")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataDirectoryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultDomainName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultLandingPage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultViewMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultWinRmPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscordWebhookUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiskAlertThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableRbac")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HealthCheckInterval")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFirstRunSetup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("MaintenanceMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxConcurrentSessions")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MfaRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotificationEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginCategories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PsExecutionPolicy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RamAlertThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireHttpsForRemote")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScriptLibraryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionTimeout")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowStatusBadges")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SidebarState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SlackWebhookUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TelemetryRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TerminalTheme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrustRelationshipPresets")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UiDensity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WebBindingPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebhookUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = "global",
                            AccentColor = "",
                            AdSyncInterval = 60,
                            AlertQuietHours = "",
                            AnimationsEnabled = true,
                            AppLoginMethod = "Local",
                            AppName = "NEXUS",
                            AppSubtitle = "Horizon UI Shell",
                            AuditLoggingEnabled = false,
                            AutoRefreshInterval = 30,
                            CompanyLogoUrl = "",
                            CpuAlertThreshold = 90,
                            DashboardLayout = "",
                            DataDirectoryPath = "",
                            DefaultDomainName = "nvlabs.com",
                            DefaultLandingPage = "dashboard",
                            DefaultViewMode = "list",
                            DefaultWinRmPort = 5985,
                            DiscordWebhookUrl = "",
                            DiskAlertThreshold = 90,
                            EnableRbac = false,
                            HealthCheckInterval = 60,
                            IsFirstRunSetup = true,
                            Language = "en-US",
                            LogFilePath = "",
                            LogLevel = "info",
                            MaintenanceMode = false,
                            MaxConcurrentSessions = 10,
                            MfaRequired = false,
                            NotificationEmail = "",
                            PluginCategories = "Management,Security,Infrastructure,Advanced",
                            PsExecutionPolicy = "RemoteSigned",
                            RamAlertThreshold = 90,
                            RequireHttpsForRemote = false,
                            ScriptLibraryPath = "",
                            SessionTimeout = 30,
                            ShowStatusBadges = true,
                            SidebarState = "expanded",
                            SlackWebhookUrl = "",
                            TelemetryRetentionDays = 30,
                            TerminalTheme = "nexus-dark",
                            Theme = "dark",
                            TimeZoneFormat = "UTC",
                            TrustRelationshipPresets = "",
                            UiDensity = "comfortable",
                            WebBindingPort = 5011,
                            WebhookUrl = ""
                        });
                });

            modelBuilder.Entity("Nexus.Gateway.Models.DiskModel", b =>
                {
                    b.Property<int>("DbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartitionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SizeGB")
                        .HasColumnType("REAL");

                    b.HasKey("DbId");

                    b.HasIndex("ServerIp");

                    b.ToTable("Disks");
                });

            modelBuilder.Entity("Nexus.Gateway.Models.InstalledAppEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstallDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeMB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UninstallString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerIp");

                    b.ToTable("InstalledApps");
                });

            modelBuilder.Entity("Nexus.Gateway.Models.NotificationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Nexus.Gateway.Models.PerfSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cpu")
                        .HasColumnType("REAL");

                    b.Property<double>("DiskR")
                        .HasColumnType("REAL");

                    b.Property<double>("DiskW")
                        .HasColumnType("REAL");

                    b.Property<double>("Mem")
                        .HasColumnType("REAL");

                    b.Property<double>("NetIn")
                        .HasColumnType("REAL");

                    b.Property<double>("NetOut")
                        .HasColumnType("REAL");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("T")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServerIp", "T");

                    b.ToTable("PerfSamples");
                });

            modelBuilder.Entity("Nexus.Gateway.Models.PluginEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScriptContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScriptType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetRoute")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Plugins");

                    b.HasData(
                        new
                        {
                            Id = "builtin-processes",
                            Author = "Custom",
                            Category = "Management",
                            Description = "Manage running processes",
                            Icon = "app-window",
                            IsActive = true,
                            IsBuiltIn = true,
                            Name = "Processes",
                            ScriptContent = "",
                            ScriptType = "powershell",
                            SourceType = "inline",
                            TargetRoute = "/processes"
                        },
                        new
                        {
                            Id = "builtin-services",
                            Author = "Custom",
                            Category = "Management",
                            Description = "Manage Windows Services",
                            Icon = "cog",
                            IsActive = true,
                            IsBuiltIn = true,
                            Name = "Services",
                            ScriptContent = "",
                            ScriptType = "powershell",
                            SourceType = "inline",
                            TargetRoute = "/services"
                        },
                        new
                        {
                            Id = "builtin-storage",
                            Author = "Custom",
                            Category = "Management",
                            Description = "Manage logical volumes and disks",
                            Icon = "hard-drive",
                            IsActive = true,
                            IsBuiltIn = true,
                            Name = "Storage",
                            ScriptContent = "",
                            ScriptType = "powershell",
                            SourceType = "inline",
                            TargetRoute = "/storage"
                        },
                        new
                        {
                            Id = "builtin-files",
                            Author = "Custom",
                            Category = "Management",
                            Description = "File Explorer",
                            Icon = "folder-open",
                            IsActive = true,
                            IsBuiltIn = true,
                            Name = "Files",
                            ScriptContent = "",
                            ScriptType = "powershell",
                            SourceType = "inline",
                            TargetRoute = "/files"
                        },
                        new
                        {
                            Id = "builtin-tasks",
                            Author = "Custom",
                            Category = "Management",
                            Description = "Task Scheduler",
                            Icon = "calendar",
                            IsActive = true,
                            IsBuiltIn = true,
                            Name = "Scheduled Tasks",
                            ScriptContent = "",
                            ScriptType = "powershell",
                            SourceType = "inline",
                            TargetRoute = "/tasks"
                        },
                        new
                        {
                            Id = "builtin-apps",
                            Author = "Custom",
                            Category = "Management",
                            Description = "Installed Programs",
                            Icon = "package",
                            IsActive = true,
                            IsBuiltIn = true,
                            Name = "Installed Apps",
                            ScriptContent = "",
                            ScriptType = "powershell",
                            SourceType = "inline",
                            TargetRoute = "/apps"
                        },
                        new
                        {
                            Id = "builtin-roles",
                            Author = "Custom",
                            Category = "Management",
                            Description = "Windows Server Roles",
                            Icon = "layers",
                            IsActive = true,
                            IsBuiltIn = true,
                            Name = "Roles & Features",
                            ScriptContent = "",
                            ScriptType = "powershell",
                            SourceType = "inline",
                            TargetRoute = "/roles"
                        },
                        new
                        {
                            Id = "builtin-updates",
                            Author = "Custom",
                            Category = "Management",
                            Description = "Patch Management",
                            Icon = "refresh-cw",
                            IsActive = true,
                            IsBuiltIn = true,
                            Name = "Windows Update",
                            ScriptContent = "",
                            ScriptType = "powershell",
                            SourceType = "inline",
                            TargetRoute = "/updates"
                        },
                        new
                        {
                            Id = "builtin-rdp",
                            Author = "Custom",
                            Category = "Management",
                            Description = "RDP Sessions",
                            Icon = "monitor",
                            IsActive = true,
                            IsBuiltIn = true,
                            Name = "Remote Desktop",
                            ScriptContent = "",
                            ScriptType = "powershell",
                            SourceType = "inline",
                            TargetRoute = "/remote-desktop"
                        },
                        new
                        {
                            Id = "builtin-firewall",
                            Author = "Custom",
                            Category = "Security",
                            Description = "Windows Defender Firewall",
                            Icon = "shield",
                            IsActive = true,
                            IsBuiltIn = true,
                            Name = "Firewall",
                            ScriptContent = "",
                            ScriptType = "powershell",
                            SourceType = "inline",
                            TargetRoute = "/firewall"
                        },
                        new
                        {
                            Id = "builtin-certs",
                            Author = "Custom",
                            Category = "Security",
                            Description = "Certificate Manager",
                            Icon = "badge-check",
                            IsActive = true,
                            IsBuiltIn = true,
                            Name = "Certificates",
                            ScriptContent = "",
                            ScriptType = "powershell",
                            SourceType = "inline",
                            TargetRoute = "/certificates"
                        },
                        new
                        {
                            Id = "builtin-users",
                            Author = "Custom",
                            Category = "Security",
                            Description = "User Management",
                            Icon = "users",
                            IsActive = true,
                            IsBuiltIn = true,
                            Name = "Local Users & Groups",
                            ScriptContent = "",
                            ScriptType = "powershell",
                            SourceType = "inline",
                            TargetRoute = "/users"
                        },
                        new
                        {
                            Id = "builtin-security",
                            Author = "Custom",
                            Category = "Security",
                            Description = "Security Event Logs",
                            Icon = "key-round",
                            IsActive = true,
                            IsBuiltIn = true,
                            Name = "Security Events",
                            ScriptContent = "",
                            ScriptType = "powershell",
                            SourceType = "inline",
                            TargetRoute = "/security"
                        },
                        new
                        {
                            Id = "builtin-networks",
                            Author = "Custom",
                            Category = "Infrastructure",
                            Description = "Network Interfaces",
                            Icon = "network",
                            IsActive = true,
                            IsBuiltIn = true,
                            Name = "Networks",
                            ScriptContent = "",
                            ScriptType = "powershell",
                            SourceType = "inline",
                            TargetRoute = "/networks"
                        },
                        new
                        {
                            Id = "builtin-devices",
                            Author = "Custom",
                            Category = "Infrastructure",
                            Description = "Device Manager",
                            Icon = "cpu",
                            IsActive = true,
                            IsBuiltIn = true,
                            Name = "Devices",
                            ScriptContent = "",
                            ScriptType = "powershell",
                            SourceType = "inline",
                            TargetRoute = "/devices"
                        },
                        new
                        {
                            Id = "builtin-registry",
                            Author = "Custom",
                            Category = "Infrastructure",
                            Description = "Registry Editor",
                            Icon = "database-zap",
                            IsActive = true,
                            IsBuiltIn = true,
                            Name = "Registry",
                            ScriptContent = "",
                            ScriptType = "powershell",
                            SourceType = "inline",
                            TargetRoute = "/registry"
                        },
                        new
                        {
                            Id = "builtin-vms",
                            Author = "Custom",
                            Category = "Infrastructure",
                            Description = "Hyper-V VMs",
                            Icon = "server",
                            IsActive = true,
                            IsBuiltIn = true,
                            Name = "Virtual Machines",
                            ScriptContent = "",
                            ScriptType = "powershell",
                            SourceType = "inline",
                            TargetRoute = "/vms"
                        },
                        new
                        {
                            Id = "builtin-vswitches",
                            Author = "Custom",
                            Category = "Infrastructure",
                            Description = "Hyper-V Switches",
                            Icon = "git-branch",
                            IsActive = true,
                            IsBuiltIn = true,
                            Name = "Virtual Switches",
                            ScriptContent = "",
                            ScriptType = "powershell",
                            SourceType = "inline",
                            TargetRoute = "/vswitches"
                        },
                        new
                        {
                            Id = "builtin-replica",
                            Author = "Custom",
                            Category = "Infrastructure",
                            Description = "Storage Replica status",
                            Icon = "copy-slash",
                            IsActive = true,
                            IsBuiltIn = true,
                            Name = "Storage Replica",
                            ScriptContent = "",
                            ScriptType = "powershell",
                            SourceType = "inline",
                            TargetRoute = "/storage-replica"
                        },
                        new
                        {
                            Id = "builtin-powershell",
                            Author = "Custom",
                            Category = "Advanced",
                            Description = "Interactive Terminal",
                            Icon = "terminal",
                            IsActive = true,
                            IsBuiltIn = true,
                            Name = "PowerShell",
                            ScriptContent = "",
                            ScriptType = "powershell",
                            SourceType = "inline",
                            TargetRoute = "/powershell"
                        },
                        new
                        {
                            Id = "builtin-events",
                            Author = "Custom",
                            Category = "Advanced",
                            Description = "Windows Event Logs",
                            Icon = "scroll-text",
                            IsActive = true,
                            IsBuiltIn = true,
                            Name = "Event Viewer",
                            ScriptContent = "",
                            ScriptType = "powershell",
                            SourceType = "inline",
                            TargetRoute = "/events"
                        });
                });

            modelBuilder.Entity("Nexus.Gateway.Models.ProcessModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandLine")
                        .HasColumnType("TEXT");

                    b.Property<double>("Cpu")
                        .HasColumnType("REAL");

                    b.Property<string>("ExecutablePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("Handles")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MemMB")
                        .HasColumnType("REAL");

                    b.Property<double>("MemPct")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Pid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Threads")
                        .HasColumnType("INTEGER");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerIp");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("Nexus.Gateway.Models.SecurityEventLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerIp");

                    b.HasIndex("ServerIp", "TimeCreated");

                    b.ToTable("SecurityEventLogs");
                });

            modelBuilder.Entity("Nexus.Gateway.Models.SecuritySnapshot", b =>
                {
                    b.Property<string>("ServerIp")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLogins24h")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalAdminsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenPortsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ServerIp");

                    b.ToTable("SecuritySnapshots");
                });

            modelBuilder.Entity("Nexus.Gateway.Models.Server", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("Cpu")
                        .HasColumnType("REAL");

                    b.Property<double>("Disk")
                        .HasColumnType("REAL");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdFetched")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Mem")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Uptime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("Nexus.Gateway.Models.VolumeModel", b =>
                {
                    b.Property<int>("DbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiskId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Letter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SizeGB")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("UsedGB")
                        .HasColumnType("REAL");

                    b.HasKey("DbId");

                    b.HasIndex("ServerIp");

                    b.ToTable("Volumes");
                });

            modelBuilder.Entity("Nexus.Gateway.Models.WindowsRoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServerRoles");
                });

            modelBuilder.Entity("Nexus.Gateway.Models.WindowsUpdateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("MaxDownloadSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServerUpdates");
                });
#pragma warning restore 612, 618
        }
    }
}
