/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VswitchesRouteImport } from './routes/vswitches'
import { Route as VmsRouteImport } from './routes/vms'
import { Route as UsersRouteImport } from './routes/users'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as StorageReplicaRouteImport } from './routes/storage-replica'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as RemoteDesktopRouteImport } from './routes/remote-desktop'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as ProcessesRouteImport } from './routes/processes'
import { Route as PowershellRouteImport } from './routes/powershell'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as NetworksRouteImport } from './routes/networks'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FirewallRouteImport } from './routes/firewall'
import { Route as FilesRouteImport } from './routes/files'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PluginIdRouteImport } from './routes/plugin.$id'

const VswitchesRoute = VswitchesRouteImport.update({
  id: '/vswitches',
  path: '/vswitches',
  getParentRoute: () => rootRouteImport,
} as any)
const VmsRoute = VmsRouteImport.update({
  id: '/vms',
  path: '/vms',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageReplicaRoute = StorageReplicaRouteImport.update({
  id: '/storage-replica',
  path: '/storage-replica',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteDesktopRoute = RemoteDesktopRouteImport.update({
  id: '/remote-desktop',
  path: '/remote-desktop',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessesRoute = ProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => rootRouteImport,
} as any)
const PowershellRoute = PowershellRouteImport.update({
  id: '/powershell',
  path: '/powershell',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworksRoute = NetworksRouteImport.update({
  id: '/networks',
  path: '/networks',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FirewallRoute = FirewallRouteImport.update({
  id: '/firewall',
  path: '/firewall',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginIdRoute = PluginIdRouteImport.update({
  id: '/plugin/$id',
  path: '/plugin/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/certificates': typeof CertificatesRoute
  '/devices': typeof DevicesRoute
  '/events': typeof EventsRoute
  '/files': typeof FilesRoute
  '/firewall': typeof FirewallRoute
  '/login': typeof LoginRoute
  '/networks': typeof NetworksRoute
  '/performance': typeof PerformanceRoute
  '/plugins': typeof PluginsRoute
  '/powershell': typeof PowershellRoute
  '/processes': typeof ProcessesRoute
  '/registry': typeof RegistryRoute
  '/remote-desktop': typeof RemoteDesktopRoute
  '/roles': typeof RolesRoute
  '/security': typeof SecurityRoute
  '/servers': typeof ServersRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/storage-replica': typeof StorageReplicaRoute
  '/tasks': typeof TasksRoute
  '/updates': typeof UpdatesRoute
  '/users': typeof UsersRoute
  '/vms': typeof VmsRoute
  '/vswitches': typeof VswitchesRoute
  '/plugin/$id': typeof PluginIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/certificates': typeof CertificatesRoute
  '/devices': typeof DevicesRoute
  '/events': typeof EventsRoute
  '/files': typeof FilesRoute
  '/firewall': typeof FirewallRoute
  '/login': typeof LoginRoute
  '/networks': typeof NetworksRoute
  '/performance': typeof PerformanceRoute
  '/plugins': typeof PluginsRoute
  '/powershell': typeof PowershellRoute
  '/processes': typeof ProcessesRoute
  '/registry': typeof RegistryRoute
  '/remote-desktop': typeof RemoteDesktopRoute
  '/roles': typeof RolesRoute
  '/security': typeof SecurityRoute
  '/servers': typeof ServersRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/storage-replica': typeof StorageReplicaRoute
  '/tasks': typeof TasksRoute
  '/updates': typeof UpdatesRoute
  '/users': typeof UsersRoute
  '/vms': typeof VmsRoute
  '/vswitches': typeof VswitchesRoute
  '/plugin/$id': typeof PluginIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/certificates': typeof CertificatesRoute
  '/devices': typeof DevicesRoute
  '/events': typeof EventsRoute
  '/files': typeof FilesRoute
  '/firewall': typeof FirewallRoute
  '/login': typeof LoginRoute
  '/networks': typeof NetworksRoute
  '/performance': typeof PerformanceRoute
  '/plugins': typeof PluginsRoute
  '/powershell': typeof PowershellRoute
  '/processes': typeof ProcessesRoute
  '/registry': typeof RegistryRoute
  '/remote-desktop': typeof RemoteDesktopRoute
  '/roles': typeof RolesRoute
  '/security': typeof SecurityRoute
  '/servers': typeof ServersRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/storage-replica': typeof StorageReplicaRoute
  '/tasks': typeof TasksRoute
  '/updates': typeof UpdatesRoute
  '/users': typeof UsersRoute
  '/vms': typeof VmsRoute
  '/vswitches': typeof VswitchesRoute
  '/plugin/$id': typeof PluginIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/certificates'
    | '/devices'
    | '/events'
    | '/files'
    | '/firewall'
    | '/login'
    | '/networks'
    | '/performance'
    | '/plugins'
    | '/powershell'
    | '/processes'
    | '/registry'
    | '/remote-desktop'
    | '/roles'
    | '/security'
    | '/servers'
    | '/services'
    | '/settings'
    | '/storage'
    | '/storage-replica'
    | '/tasks'
    | '/updates'
    | '/users'
    | '/vms'
    | '/vswitches'
    | '/plugin/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/certificates'
    | '/devices'
    | '/events'
    | '/files'
    | '/firewall'
    | '/login'
    | '/networks'
    | '/performance'
    | '/plugins'
    | '/powershell'
    | '/processes'
    | '/registry'
    | '/remote-desktop'
    | '/roles'
    | '/security'
    | '/servers'
    | '/services'
    | '/settings'
    | '/storage'
    | '/storage-replica'
    | '/tasks'
    | '/updates'
    | '/users'
    | '/vms'
    | '/vswitches'
    | '/plugin/$id'
  id:
    | '__root__'
    | '/'
    | '/apps'
    | '/certificates'
    | '/devices'
    | '/events'
    | '/files'
    | '/firewall'
    | '/login'
    | '/networks'
    | '/performance'
    | '/plugins'
    | '/powershell'
    | '/processes'
    | '/registry'
    | '/remote-desktop'
    | '/roles'
    | '/security'
    | '/servers'
    | '/services'
    | '/settings'
    | '/storage'
    | '/storage-replica'
    | '/tasks'
    | '/updates'
    | '/users'
    | '/vms'
    | '/vswitches'
    | '/plugin/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsRoute: typeof AppsRoute
  CertificatesRoute: typeof CertificatesRoute
  DevicesRoute: typeof DevicesRoute
  EventsRoute: typeof EventsRoute
  FilesRoute: typeof FilesRoute
  FirewallRoute: typeof FirewallRoute
  LoginRoute: typeof LoginRoute
  NetworksRoute: typeof NetworksRoute
  PerformanceRoute: typeof PerformanceRoute
  PluginsRoute: typeof PluginsRoute
  PowershellRoute: typeof PowershellRoute
  ProcessesRoute: typeof ProcessesRoute
  RegistryRoute: typeof RegistryRoute
  RemoteDesktopRoute: typeof RemoteDesktopRoute
  RolesRoute: typeof RolesRoute
  SecurityRoute: typeof SecurityRoute
  ServersRoute: typeof ServersRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  StorageRoute: typeof StorageRoute
  StorageReplicaRoute: typeof StorageReplicaRoute
  TasksRoute: typeof TasksRoute
  UpdatesRoute: typeof UpdatesRoute
  UsersRoute: typeof UsersRoute
  VmsRoute: typeof VmsRoute
  VswitchesRoute: typeof VswitchesRoute
  PluginIdRoute: typeof PluginIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vswitches': {
      id: '/vswitches'
      path: '/vswitches'
      fullPath: '/vswitches'
      preLoaderRoute: typeof VswitchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vms': {
      id: '/vms'
      path: '/vms'
      fullPath: '/vms'
      preLoaderRoute: typeof VmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage-replica': {
      id: '/storage-replica'
      path: '/storage-replica'
      fullPath: '/storage-replica'
      preLoaderRoute: typeof StorageReplicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote-desktop': {
      id: '/remote-desktop'
      path: '/remote-desktop'
      fullPath: '/remote-desktop'
      preLoaderRoute: typeof RemoteDesktopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processes': {
      id: '/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof ProcessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/powershell': {
      id: '/powershell'
      path: '/powershell'
      fullPath: '/powershell'
      preLoaderRoute: typeof PowershellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/networks': {
      id: '/networks'
      path: '/networks'
      fullPath: '/networks'
      preLoaderRoute: typeof NetworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firewall': {
      id: '/firewall'
      path: '/firewall'
      fullPath: '/firewall'
      preLoaderRoute: typeof FirewallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugin/$id': {
      id: '/plugin/$id'
      path: '/plugin/$id'
      fullPath: '/plugin/$id'
      preLoaderRoute: typeof PluginIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsRoute: AppsRoute,
  CertificatesRoute: CertificatesRoute,
  DevicesRoute: DevicesRoute,
  EventsRoute: EventsRoute,
  FilesRoute: FilesRoute,
  FirewallRoute: FirewallRoute,
  LoginRoute: LoginRoute,
  NetworksRoute: NetworksRoute,
  PerformanceRoute: PerformanceRoute,
  PluginsRoute: PluginsRoute,
  PowershellRoute: PowershellRoute,
  ProcessesRoute: ProcessesRoute,
  RegistryRoute: RegistryRoute,
  RemoteDesktopRoute: RemoteDesktopRoute,
  RolesRoute: RolesRoute,
  SecurityRoute: SecurityRoute,
  ServersRoute: ServersRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  StorageRoute: StorageRoute,
  StorageReplicaRoute: StorageReplicaRoute,
  TasksRoute: TasksRoute,
  UpdatesRoute: UpdatesRoute,
  UsersRoute: UsersRoute,
  VmsRoute: VmsRoute,
  VswitchesRoute: VswitchesRoute,
  PluginIdRoute: PluginIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
